#!/bin/bash
set -e

# Comrad Watch — Production Deployment Setup
# Generates .env with strong secrets for production Docker deployment.
#
# Usage: ./deploy.sh
#
# After running this script:
#   docker compose -f docker-compose.prod.yml up -d
#

ENV_FILE=".env"

echo ""
echo "=== COMRAD WATCH — PRODUCTION SETUP ==="
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo ".env already exists."
    read -p "Overwrite? (y/N) " confirm
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Aborted."
        exit 0
    fi
fi

# Get domain name
read -p "Enter your domain (e.g., comradwatch.org): " DOMAIN
if [ -z "$DOMAIN" ]; then
    echo "Domain is required for HTTPS. Aborting."
    exit 1
fi

# Generate strong random secrets
echo "Generating secrets..."
JWT_SECRET=$(openssl rand -hex 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -hex 16)

# Google Drive (optional)
echo ""
echo "Google Drive integration (optional — press Enter to skip):"
read -p "  GOOGLE_CLIENT_ID: " GOOGLE_CLIENT_ID
read -p "  GOOGLE_CLIENT_SECRET: " GOOGLE_CLIENT_SECRET

# Instagram (optional)
echo ""
echo "Instagram Story integration (optional — press Enter to skip):"
read -p "  INSTAGRAM_APP_ID: " INSTAGRAM_APP_ID
read -p "  INSTAGRAM_APP_SECRET: " INSTAGRAM_APP_SECRET

# Write single .env file (docker compose reads this automatically)
cat > "$ENV_FILE" << EOF
# Generated by deploy.sh — PRODUCTION
# Keep this file secret. Never commit it to git.

# Domain (used by Caddy for HTTPS + by the app for public video URLs)
DOMAIN=${DOMAIN}

# Database
DB_PASSWORD=${DB_PASSWORD}

# Auth + Encryption
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Google Drive (leave empty to disable)
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URI=https://${DOMAIN}/api/google/callback

# Instagram (leave empty to disable)
INSTAGRAM_APP_ID=${INSTAGRAM_APP_ID}
INSTAGRAM_APP_SECRET=${INSTAGRAM_APP_SECRET}
EOF

echo ""
echo "=== READY ==="
echo ""
echo "Created .env with production configuration."
echo ""
echo "Before starting, make sure:"
echo "  1. Your domain ($DOMAIN) DNS points to this server's IP"
echo "  2. Ports 80, 443, and 1935 are open in your firewall"
echo ""
echo "Start the server:"
echo ""
echo "  docker compose -f docker-compose.prod.yml up -d"
echo ""
echo "Caddy will automatically get an HTTPS certificate from Let's Encrypt."
echo "Your app will be live at https://${DOMAIN}"
echo ""
