#!/bin/bash
set -e

# Comrad Watch — Local Development Setup
# Generates .env with random secrets and starts PostgreSQL via Docker.
#
# Usage: ./setup.sh
#
# IMPORTANT: Docker is the recommended way to run Comrad Watch.
# Running without Docker requires PostgreSQL, Go 1.25+, and FFmpeg
# installed manually. If you're not sure, just use Docker:
#
#   docker compose up --build
#

ENV_FILE="backend/.env"

echo ""
echo "=== COMRAD WATCH — LOCAL DEV SETUP ==="
echo ""

# Check if .env already exists
if [ -f "$ENV_FILE" ]; then
    echo "backend/.env already exists. Delete it first if you want to regenerate."
    echo ""
    exit 0
fi

# Generate random secrets
echo "Generating secrets..."
JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64)
ENCRYPTION_KEY=$(openssl rand -hex 32 2>/dev/null || head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64)

# Write .env file
cat > "$ENV_FILE" << EOF
# Generated by setup.sh — local development only
# For production, use deploy.sh instead

# Server
HTTP_PORT=8080
RTMP_PORT=1935

# Database
DATABASE_URL=postgres://comradwatch:devpassword@localhost:5432/comradwatch?sslmode=disable

# Auth + Encryption (auto-generated, safe for local dev)
JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# Storage
SEGMENT_DIR=./segments
PUBLIC_HOST=localhost

# Google Drive (optional — leave empty to skip)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=http://localhost:8080/api/google/callback

# Instagram (optional — leave empty to skip)
INSTAGRAM_APP_ID=
INSTAGRAM_APP_SECRET=
EOF

echo "Created backend/.env with random secrets."

# Start PostgreSQL via Docker (the only sane way)
if command -v docker &>/dev/null; then
    echo ""
    echo "Starting PostgreSQL via Docker..."
    docker compose up -d db 2>/dev/null || docker-compose up -d db 2>/dev/null
    echo "PostgreSQL running on localhost:5432"
    echo ""
    echo "=== READY ==="
    echo ""
    echo "  cd backend && go run ./cmd/server"
    echo ""
    echo "  Then open http://localhost:8080"
    echo ""
    echo "Or just use Docker for everything (recommended):"
    echo ""
    echo "  docker compose up --build"
    echo ""
elif command -v createdb &>/dev/null; then
    echo ""
    echo "Docker not found. Trying local PostgreSQL..."
    createdb comradwatch 2>/dev/null && echo "Database 'comradwatch' created." || echo "Database 'comradwatch' may already exist (that's fine)."
    echo ""
    echo "=== READY ==="
    echo ""
    echo "  cd backend && go run ./cmd/server"
    echo ""
    echo "  Then open http://localhost:8080"
    echo ""
else
    echo ""
    echo "WARNING: Neither Docker nor PostgreSQL found."
    echo "Install Docker (recommended) or PostgreSQL, then run this script again."
    echo ""
    echo "Docker: https://docs.docker.com/get-docker/"
    echo ""
fi
