@echo off
setlocal EnableDelayedExpansion

REM Comrad Watch — Local Development Setup (Windows)
REM Generates .env with random secrets and starts PostgreSQL via Docker.
REM
REM Usage: setup.bat
REM
REM IMPORTANT: Docker is the recommended way to run Comrad Watch.
REM Running without Docker requires PostgreSQL, Go 1.25+, and FFmpeg
REM installed manually. If you're not sure, just use Docker:
REM
REM   docker compose up --build

echo.
echo === COMRAD WATCH — LOCAL DEV SETUP ===
echo.

REM Check if .env already exists
if exist "backend\.env" (
    echo backend\.env already exists. Delete it first if you want to regenerate.
    echo.
    exit /b 0
)

REM Generate random secrets using PowerShell
echo Generating secrets...
for /f "delims=" %%i in ('powershell -Command "[System.BitConverter]::ToString((1..32 | ForEach-Object { [byte](Get-Random -Maximum 256) })).Replace('-','')"') do set JWT_SECRET=%%i
for /f "delims=" %%i in ('powershell -Command "[System.BitConverter]::ToString((1..32 | ForEach-Object { [byte](Get-Random -Maximum 256) })).Replace('-','')"') do set ENCRYPTION_KEY=%%i

REM Write .env file
(
echo # Generated by setup.bat — local development only
echo # For production, use deploy.sh instead
echo.
echo # Server
echo HTTP_PORT=8080
echo RTMP_PORT=1935
echo.
echo # Database
echo DATABASE_URL=postgres://comradwatch:devpassword@localhost:5432/comradwatch?sslmode=disable
echo.
echo # Auth + Encryption ^(auto-generated, safe for local dev^)
echo JWT_SECRET=!JWT_SECRET!
echo ENCRYPTION_KEY=!ENCRYPTION_KEY!
echo.
echo # Storage
echo SEGMENT_DIR=./segments
echo PUBLIC_HOST=localhost
echo.
echo # Google Drive ^(optional — leave empty to skip^)
echo GOOGLE_CLIENT_ID=
echo GOOGLE_CLIENT_SECRET=
echo GOOGLE_REDIRECT_URI=http://localhost:8080/api/google/callback
echo.
echo # Instagram ^(optional — leave empty to skip^)
echo INSTAGRAM_APP_ID=
echo INSTAGRAM_APP_SECRET=
) > "backend\.env"

echo Created backend\.env with random secrets.

REM Start PostgreSQL via Docker
where docker >nul 2>nul
if %ERRORLEVEL% equ 0 (
    echo.
    echo Starting PostgreSQL via Docker...
    docker compose up -d db 2>nul || docker-compose up -d db 2>nul
    echo PostgreSQL running on localhost:5432
    echo.
    echo === READY ===
    echo.
    echo   cd backend ^&^& go run ./cmd/server
    echo.
    echo   Then open http://localhost:8080
    echo.
    echo Or just use Docker for everything ^(recommended^):
    echo.
    echo   docker compose up --build
    echo.
) else (
    echo.
    echo WARNING: Docker not found.
    echo Install Docker ^(recommended^) then run this script again.
    echo.
    echo Docker: https://docs.docker.com/get-docker/
    echo.
)

endlocal
